### ISSUE TITLE
Installation steps lead to warning message on MacOS

### ISSUE THREAD

**Issue by magicznyleszek** [zim0369/pretty-kitty#3]
**Describe the bug**
When installing on case-insensitive filesystem, there are some paths that are colliding.

**To Reproduce**
1. Check out the installation instructions from this repo
2. Run first step: `git clone https://github.com/zim0369/pretty-kitty $HOME/pretty-kitty`
3. See error

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
Full warning message:
```
git clone https://github.com/zim0369/pretty-kitty $HOME/pretty-kitty
Cloning into '/Users/leszek/pretty-kitty'...
remote: Enumerating objects: 531, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 531 (delta 9), reused 16 (delta 7), pack-reused 506
Receiving objects: 100% (531/531), 10.24 MiB | 3.92 MiB/s, done.
Resolving deltas: 100% (141/141), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'colors/dark/Tomorrow_Night.conf'
  'colors/dark/Tomorrow_night.conf'
```

**Comment by magicznyleszek** [comment]
@zim0369 I can confirm that the warning is no longer happening 👌

**Comment by txtyash** [comment]
keeping linux only
