### ISSUE TITLE
Can't use it due to colors.conf file not existing

### ISSUE THREAD

**Issue by magicznyleszek** [zim0369/pretty-kitty#4]
**Describe the bug**
When trying to set font size with `pkitty` the program crashes.

**To Reproduce**
1. Run `pkitty`
2. Select option `s` (font size)
3. Type a value and press ENTER

**Expected behavior**
Should just work™

**Actual behavior**
I get this error:
```
     ♥  Setting size to: 14
     !  Please Restart Kitty
     ✔️  Reloading Settings...Traceback (most recent call last):
  File "lib/python3.9/kitty/rc/set_colors.py", line 98, in message_to_kitty
  File "lib/python3.9/kitty/rc/set_colors.py", line 43, in parse_colors
FileNotFoundError: [Errno 2] No such file or directory: '/Users/leszek/.config/kitty/colors.conf'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/python3.9/kitty/remote_control.py", line 479, in main
  File "lib/python3.9/kitty/rc/set_colors.py", line 100, in message_to_kitty
kitty.rc.base.ParsingOfArgsFailed: The colors configuration file /Users/leszek/.config/kitty/colors.conf was not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/python3.9/runpy.py", line 197, in _run_module_as_main
  File "lib/python3.9/runpy.py", line 87, in _run_code
  File "lib/python3.9/kitty_main.py", line 7, in <module>
  File "lib/python3.9/kitty/entry_points.py", line 186, in main
  File "lib/python3.9/kitty/entry_points.py", line 23, in remote_control
  File "lib/python3.9/kitty/remote_control.py", line 481, in main
NameError: name 'exit' is not defined
```

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by txtyash** [comment]
These errors are occurring mostly because this script was never tested on mac. I'll try to fix this ASAP. I might also need a little help if you're willing to.

**Comment by magicznyleszek** [comment]
Oh ok, I assumed it was ok, because of "BTW, Doesn't work on WINDOWS" text in readme 😅 I can help, sure 👌

**Comment by txtyash** [comment]
@magicznyleszek  If you're familiar with bash can you do some work on mac side? I don't have enough time and resources right now to add support for MacOS.

I'm sadly going to have to discontinue support for MacOS(which I assumed out of nowhere would work fine). If you wish to maintain this script for MacOS then that'd be really great or you can just maintain a fork for yourself.

If all this sounds tedious then I'd suggest trying out https://github.com/lemnos/theme.sh

I'm also closing #3

**Comment by magicznyleszek** [comment]
@zim0369 I will see if I am capable of doing it 😅 For now I think you should update readme to warn other people about lack of MacOS support 👌

**Comment by txtyash** [comment]
@magicznyleszek I have made some changes that **might** fix your problem. I request you to do the following:
1. Navigate to the cloned pretty-kitty dir and run the `uninstall` script else manually remove the `pkitty` binary
2. Reinstall pretty-kitty 
3. Let me know how it went

**Comment by magicznyleszek** [comment]
@zim0369 no errors :)

**Comment by txtyash** [comment]
@magicznyleszek I'm sorry for deleting your previous comment. Seems like the github app on android has some bugs.

Did you try all the options after running `pkitty`? Do they work fine?

Other than that, I will try to fix the problems with cmdline flags today.

**Comment by txtyash** [comment]
@magicznyleszek the `shuf` isn't available on mac. I'm discontinuing macos support. Sorry for inconvenience.
