### ISSUE TITLE
Please use /opt instead of /usr/local

### ISSUE THREAD

**Issue by melMass** [zim0369/pretty-kitty#5]
**Describe the bug**
Apple pushes against using `/usr/local` now

**Expected behavior**
Either something like `~/bin` with instructions to add to path or `/opt/bin` or similar

**Comment by txtyash** [comment]
@melMass unfortunately the project isn't maintained anymore. You can try using [theme.sh](https://github.com/lemnos/theme.sh)

**Comment by melMass** [comment]
> @melMass unfortunately the project isn't maintained anymore. You can try using [theme.sh](https://github.com/lemnos/theme.sh)

Oops I should have read before I just made a PR, thanks

**Comment by melMass** [comment]
For anyone coming from google, I ended up wrapping the default `kitty +kitten themes` with `kitty @ set-colors --all --configured $theme_path` and it works well
